version: '3.7'
services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - '15673:15672'
      - '5673:5672'
    environment:
      RABBITMQ_USERNAME: root
      RABBITMQ_PASSWORD: root