version: '3.7'
services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - '15673:15672'
      - '5673:5672'
    environment:
      RABBITMQ_USERNAME: root
      RABBITMQ_PASSWORD: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '16379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"